### ISSUE TITLE
Plug-in works only for one the tab list occurance in a page

### ISSUE THREAD

**Issue by IdanAdar** [kattunga/Bootstrap-Dynamic-Tabs#2]
I have a page that contains two sets of tabs:

``` html
[tab-bar-item active][tab-bar-item][tab-bar-item]
..
...
....
[tab-bar-item][tab-bar-item]
```

As you can see, in the active tab bar items, there is another set of tabs.
What happens is that only the inner tablist becomes responsive, yet the top does not.

I hope you understand the issue I mentioned.

**Comment by kattunga** [comment]
please could you fork the project and add a functional demo to see the issue?

**Comment by IdanAdar** [comment]
Sorry, I've replaced libs and no longer have an implementation of this issue... you can close this issue...
